version: "3"

volumes:
  dn_01_data:
  nn_01_data:
  mysql_data:
  presto_data:

services:
  namenode:
    image: "matthewcmead/cloudera-cdh-namenode:cdh-5.14.2"
    volumes:
    - nn_01_data:/hdfs
    ports:
     - "8020:8020"
    networks:
      - hadoop
    restart: unless-stopped

  yarnmaster:
    image: "matthewcmead/cloudera-cdh-yarnmaster:cdh-5.14.2"
    ports:
     - "8032:8032"
     - "8088:8088"
    networks:
      - hadoop
    restart: unless-stopped

  datanode01:
    image: "matthewcmead/cloudera-cdh-datanode:cdh-5.14.2"
    volumes:
    - dn_01_data:/hdfs
    ports:
     - "50020:50020"
     - "50075:50075"
     - "8042:8042"
    networks:
      - hadoop
    depends_on:
      - namenode
      - yarnmaster
    restart: unless-stopped

  edgenode:
    image: "matthewcmead/cloudera-cdh-edgenode:cdh-5.14.2"
#    volumes:
#    - pgdata:/var/lib/postgresql
#    ports:
#     - "50020:50020"
#     - "50075:50075"
#     - "8042:8042"
    networks:
      - hadoop
    depends_on:
      - namenode
      - yarnmaster
    command: /bin/true

  mysql:
    image: "centos/mysql-56-centos7"
    volumes:
      - mysql_data:/var/lib/mysql/data
    ports:
      - "3306:3306"
    networks:
      - hadoop
    environment:
      - MYSQL_USER=hive
      - MYSQL_PASSWORD=cloudera
      - MYSQL_DATABASE=metastore
      - MYSQL_ROOT_PASSWORD=cloudera
    restart: unless-stopped

  hivemetastore:
    image: "matthewcmead/cloudera-cdh-hivemetastore:cdh-5.14.2"
    ports:
     - "9083:9083"
    networks:
      - hadoop
    depends_on:
      - namenode
      - yarnmaster
      - mysql
    restart: unless-stopped

  presto:
    image: "matthewcmead/cloudera-cdh-presto:cdh-5.14.2"
    volumes:
      - presto_data:/presto/data
    ports:
      - "9876:9876"
    networks:
      - hadoop
    depends_on:
      - namenode
      - yarnmaster
      - hivemetastore
    restart: unless-stopped
    expose:
      - 9876

networks:
  hadoop:
#    internal: true
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.19.253.0/24
#  edge:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.19.254.0/24
