version: "3"

volumes:
  hms_data:
  presto_data:
  minio_data:

services:

  yarnmaster:
    image: "matthewcmead/cloudera-cdh-yarnmaster:cdh-5.14.2"
    ports:
     - "8032:8032"
     - "8088:8088"
    networks:
      - hadoop
    depends_on:
      - minio
    restart: unless-stopped

  datanode01:
    image: "matthewcmead/cloudera-cdh-datanode:cdh-5.14.2"
    ports:
     - "8042:8042"
    networks:
      - hadoop
    depends_on:
      - minio
      - yarnmaster
    restart: unless-stopped

  edgenode:
    image: "matthewcmead/cloudera-cdh-edgenode:cdh-5.14.2"
    networks:
      - hadoop
    depends_on:
      - yarnmaster
      - datanode01
      - minio
    command: /bin/true

  minio:
    image: "matthewcmead/minio-centos7:latest"
    environment:
      - MINIO_ACCESS_KEY=abc
      - MINIO_SECRET_KEY=abc12345
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
    expose:
      - 9000
    networks:
      - hadoop
    command: ["server", "/data"]
   
  hivemetastore:
    image: "matthewcmead/cloudera-cdh-hivemetastore:cdh-5.14.2"
    ports:
     - "9083:9083"
    networks:
      - hadoop
    depends_on:
      - yarnmaster
      - datanode01
    restart: unless-stopped
    volumes:
      - hms_data:/data

  presto:
    image: "matthewcmead/cloudera-cdh-presto:cdh-5.14.2"
    volumes:
      - presto_data:/presto/data
    ports:
      - "9876:9876"
    networks:
      - hadoop
    depends_on:
      - yarnmaster
      - hivemetastore
    restart: unless-stopped
    expose:
      - 9876

networks:
  hadoop:
#    internal: true
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.19.253.0/24
#  edge:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.19.254.0/24
